In [1]:
import minitorch

In [3]:
x = minitorch.tensor([1, 2, 3, 4, 5, 6]).contiguous().view(2, 3, 1)
x


[
    [
        [1.000000],
        [2.000000],
        [3.000000],
    ],
    [
        [4.000000],
        [5.000000],
        [6.000000],
    ],
]

In [ ]:
x.to_numpy()

In [ ]:
x._tensor.shape, x._tensor.strides

In [ ]:
y = minitorch.Tensor.make(
    storage=x._tensor._storage,
    shape=(2, 3),
    strides=(3, 1),
    backend=x.backend,
)

y

In [ ]:
y._tensor._storage

In [ ]:
y._tensor.shape, y._tensor.strides

In [ ]:
y._tensor._storage is x._tensor._storage

In [ ]:
z = x.view(3, 2, 1)
z

In [ ]:
z._tensor.shape, z._tensor.strides

In [ ]:
z._tensor._storage is x._tensor._storage

In [ ]:
z_index = [1, 1, 0]
pos = minitorch.index_to_position(z_index, z._tensor._strides)
z[tuple(z_index)] == z._tensor._storage[pos], pos, z[tuple(z_index)]

In [ ]:
z.shape

In [3]:
from minitorch import TensorData
import numpy as np

In [4]:
x_ = np.arange(12)
x = TensorData(x_, (2, 2, 3), (6, 3, 1))

In [5]:
print(x.to_string())


[
    [
        [0.000000 1.000000 2.000000],
        [3.000000 4.000000 5.000000],
    ],
    [
        [6.000000 7.000000 8.000000],
        [9.000000 10.000000 11.000000],
    ],
]
